repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: check-toml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/codespell-project/codespell
  rev: v2.2.6
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli
    exclude: '^\.cursor/.*\.mdc$'

- repo: https://github.com/DavidAnson/markdownlint-cli2
  rev: v0.12.1
  hooks:
    - id: markdownlint-cli2
      exclude: '^\.cursor/.*\.mdc$'

- repo: local
  hooks:
  - id: lint
    name: lint
    entry: make lint
    types: [python]
    language: system
    pass_filenames: false
