line-length = 79
target-version = "py313"
indent-width = 4
exclude = [
    ".git",
    ".venv",
    "venv",
    "build",
    "dist",
    "__pycache__",
    ".idea",
    ".pytest_cache",
    ".ruff_cache",
    ".mypy_cache",
    "htmlcov",
    ".gitignore",
    ".dockerignore",
    "Dockerfile",
    "docker-compose.yml",
    "*.md",
]

[format]

[lint]
select = [
    "N",      # pep8-naming
    "ANN",    # flake8-annotations
    "ASYNC",  # flake8-async
    "FAST",   # FastApi
    "S",      # flake8-bandit
    "BLE",    # flake8-blind-except
    "T20",    # flake8-print
    "B",      # flake8-bugbear
    "F",      # Pyflakes
    "I",      # isort
    "E",      # pycodestyle errors
    "W",      # pycodestyle warnings
    "UP",     # pyupgrade
    "A",      # builtins
    "ERA",    # erradicate
    "C4",     # flake8-comprehensions
]

ignore = [
    "ANN401",  # Allow using Any as type hint
    "S101",    # Allow using assert
    "B904",    # Allow raising exceptions without "from err"
    "W191",    # Ruff conflicting rules
    "E111",
    "E114",
    "E117",
]

[lint.per-file-ignores]
"conftest.py" = ["S"]
"test_*.py" = ["S", "ANN201"]
"scripts/**/*.py" = ["T201"]

[lint.pep8-naming]
classmethod-decorators = ["pydantic.model_validator"]

[lint.flake8-annotations]
suppress-dummy-args = true
